[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-yaml", args = ["--allow-multiple-documents"], exclude = "^helm/" },
  { id = "check-added-large-files" },
]

[[repos]]
repo = "https://github.com/golangci/golangci-lint"
rev = "v2.10.1"
hooks = [
  { id = "golangci-lint" },
]
