{{- if .Values.rbac.createLeaderElection }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-leader-election" (include "supabase-operator.fullname" .) }}
  labels:
    {{- include "supabase-operator.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-leader-election" (include "supabase-operator.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "supabase-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
