{{- if .Values.rbac.createMetrics }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-metrics-reader" (include "supabase-operator.fullname" .) }}
  labels:
    {{- include "supabase-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
{{- end }}
