{{- if .Values.rbac.createMetrics }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-metrics-auth" (include "supabase-operator.fullname" .) }}
  labels:
    {{- include "supabase-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-metrics-auth" (include "supabase-operator.fullname" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "supabase-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
