{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "supabase-operator.fullname" . }}-mutating-webhook
  labels:
    {{- include "supabase-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" .Release.Namespace (include "supabase-operator.webhookCertSecret" .) }}
webhooks:
  - name: msupabaseproject.kb.io
    admissionReviewVersions: ["v1"]
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "supabase-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-supabase-strrl-dev-v1alpha1-supabaseproject
    rules:
      - apiGroups: ["supabase.strrl.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["supabaseprojects"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "supabase-operator.fullname" . }}-validating-webhook
  labels:
    {{- include "supabase-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ printf "%s/%s" .Release.Namespace (include "supabase-operator.webhookCertSecret" .) }}
webhooks:
  - name: vsupabaseproject.kb.io
    admissionReviewVersions: ["v1"]
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "supabase-operator.webhookServiceName" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-supabase-strrl-dev-v1alpha1-supabaseproject
    rules:
      - apiGroups: ["supabase.strrl.dev"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["supabaseprojects"]
{{- end }}
